---
title: "Week 2"
output: html_document
date: "2022-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
medals<-data.frame(Country=c("USA", "GBR", "CHN"),
 Gold=c(46,27,26),
 Silver=c(37,23,18),
 Bronze=c(38,17,26))
medals
```


```{r}
medals[c(1,3),c(1,3)]
```

```{r}
library(readr)
library(tidyverse)
```

```{r}
library(ggplot2)
library(dplyr)
library(scales)
```

```{r}
crime <- estimated_crimes_1979_2020[!is.na(estimated_crimes_1979_2020$state_name),]
```

```{r}
install.packages("ggrepel")
library(ggrepel)
```

```{r}
ggplot(data = crime)+ geom_line(mapping = aes(x=year, y=robbery, colour= state_name))+theme(legend.key.size = unit(.5, 'cm'),legend.text = element_text(size=7))+labs(colour = "State names")+scale_y_continuous(breaks = pretty_breaks())
```

```{r}
ggplot(crime, aes(x = year, y =robbery, col = state_name)) +    # Draw ggplot2 plot with labels
  geom_line() +
  geom_label_repel(aes(year,robbery,label = state_name),
                   size=2.5,nudge_x = 1,direction = 'y', vjust=0,
                   na.rm = TRUE) +
  theme(legend.position = "none")
```






